services:
  fuseki:
    hostname: fuseki
    image: stain/jena-fuseki:5.1.0
    environment:
      - ADMIN_PASSWORD=admin
      - JAVA_OPTIONS=-Xmx2g -Xms1g
    ports:
      - ${FUSEKI_PORT:-9030}:3030
    volumes:
      - ./dockerfiles/config/skosmos.ttl:/fuseki/configuration/skosmos.ttl
    networks:
      - traefik

  fuseki-cache:
    hostname: fuseki-cache
    image: varnish
    ports:
      - ${CACHE_PORT:-9031}:80
    volumes:
      - type: bind
        source: ./dockerfiles/config/varnish-default.vcl
        target: /etc/varnish/default.vcl
    networks:
      - traefik

  skosmos:
    hostname: skosmos
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.ubuntu
    ports:
      - ${SKOSMOS_PORT:-9090}:80
    depends_on:
      - fuseki
      - fuseki-cache
    volumes:
      - type: bind
        source: ./dockerfiles/config/config-docker-compose.ttl
        target: /var/www/html/config.ttl
    networks:
      - traefik

networks:
  traefik:
    external: true